name: CMake Multi-Platform Build

on: [push, pull_request]

jobs:
  build:
    name: Build and Test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        compiler: [gcc, clang, msvc]
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Set up CMake
      uses: actions/setup-cmake@v2
      with:
        cmake-version: '3.20'
    
    - name: Configure and Build
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_CXX_COMPILER=${{ matrix.compiler }} ..
        cmake --build .
    
    - name: Run Tests
      run: |
        cd build
        ctest
    
    - name: Upload Artifacts
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: build
